/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AncillaryType } from './ancillaryType';

export interface Ancillary { 
    /**
     * Total price of ancillaries of this type
     */
    totalPrice: string;
    /**
     * Unique reference of the passenger associated to this ancillary
     */
    passengerReference?: string;
    type: AncillaryType;
    /**
     * Is this ancillary covered by the product. By default true if not specified
     */
    covered?: boolean;
}