/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CfarPriceType = 'ticket' | 'ancillary';

export const CfarPriceType = {
    Ticket: 'ticket' as CfarPriceType,
    Ancillary: 'ancillary' as CfarPriceType
};