/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ancillary } from './ancillary';
import { CfarItinerarySlice } from './cfarItinerarySlice';
import { CfarPassenger } from './cfarPassenger';
import { FareRule } from './fareRule';
import { PassengerPricing } from './passengerPricing';

export interface CfarItinerary { 
    /**
     * List of passengers type, count and pricing for the itinerary
     */
    passengerPricing: Array<PassengerPricing>;
    /**
     * Currency of pricing fields
     */
    currency: string;
    /**
     * List of slices of the itinerary; 1 (one way),  2 (round trip) or up to 10 (multi-destination) slices are allowed
     */
    slices: Array<CfarItinerarySlice>;
    /**
     * Ancillaries attached to the itinerary and their prices. Only ancillaries covered by CFAR must be filled
     */
    ancillaries?: Array<Ancillary>;
    /**
     * Total price to be covered by CFAR (including ancillaries if applicable)
     */
    totalPrice?: string;
    /**
     * Details of the passengers
     */
    passengers?: Array<CfarPassenger>;
    /**
     * The fare rules associated to the itinerary. If different fare rules apply to different slices in the itinerary, indicate the most restrictive.
     */
    fareRules?: Array<FareRule>;
}