/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MapString } from './mapString';

export interface CfarContents { 
    /**
     * An array containing the bullet points to be displayed
     */
    bulletPoints: Array<string>;
    labels: MapString;
}