/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CfarItinerarySliceSegment } from './cfarItinerarySliceSegment';

/**
 * An object containing the list of flight segments for a fare slice
 */
export interface CfarItinerarySlice { 
    /**
     * A list of segments which make up the slice of the fare
     */
    segments: Array<CfarItinerarySliceSegment>;
    fareBrand?: string;
}