/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CfarContractStatus = 'created' | 'confirmed' | 'canceled' | 'exercised' | 'expired';

export const CfarContractStatus = {
    Created: 'created' as CfarContractStatus,
    Confirmed: 'confirmed' as CfarContractStatus,
    Canceled: 'canceled' as CfarContractStatus,
    Exercised: 'exercised' as CfarContractStatus,
    Expired: 'expired' as CfarContractStatus
};