/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
import { PassengerType } from './passengerType';

/**
 * An object detailing the Passenger Information
 */
export interface CfarPassenger { 
    /**
     * Unique reference of the passenger
     */
    passengerReference: string;
    passengerType: PassengerType;
    /**
     * Ancillaries attached to the itinerary and their prices
     */
    firstName?: string;
    /**
     * Ancillaries attached to the itinerary and their prices
     */
    lastName?: string;
    /**
     * The birth date in ISO Local Date format
     */
    dateOfBirth?: string;
    gender?: Gender;
}