/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CfarPassengerTax { 
    /**
     * Code of the tax
     */
    code: string;
    /**
     * The amount of the tax
     */
    amount: string;
    /**
     * The currency of the tax
     */
    currency: string;
}