/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookingConfirmed1 } from './bookingConfirmed1';
import { CfarDenyPurchase } from './cfarDenyPurchase';
import { CfarEventWithContract } from './cfarEventWithContract';
import { CfarForcedChoiceWarning } from './cfarForcedChoiceWarning';
import { CfarOffersBannerDisplay } from './cfarOffersBannerDisplay';
import { CfarOffersTakeoverDisplay } from './cfarOffersTakeoverDisplay';
import { CfarViewInfo } from './cfarViewInfo';
import { OffersDisplayed1 } from './offersDisplayed1';

export type CfarEvent = BookingConfirmed1 | CfarDenyPurchase | CfarEventWithContract | CfarForcedChoiceWarning | CfarOffersBannerDisplay | CfarOffersTakeoverDisplay | CfarViewInfo | OffersDisplayed1;