/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A Refund Authorization Request
 */
export interface CreateRefundAuthorizationRequest { 
    /**
     * The user who will be refunded. This ID is the response from Create User
     */
    userId: string;
}