/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CfarItinerary } from './cfarItinerary';
import { RequestType } from './requestType';
import { UiVariant } from './uiVariant';

/**
 * A create CFAR offer request
 */
export interface CreateCfarOfferCustomerRequest { 
    itinerary: Array<CfarItinerary>;
    requestType: RequestType;
    bookingDateTime?: Date;
    uiVariant?: UiVariant;
}