/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A create CFAR refund request
 */
export interface CreateRefundRequest { 
    /**
     * trm-286646a1-69f0-4926-a849-8fe8ad79756e
     */
    transferMethodId: string;
}