/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ExerciseStepResult = 'success' | 'failure' | 'technical_error';

export const ExerciseStepResult = {
    Success: 'success' as ExerciseStepResult,
    Failure: 'failure' as ExerciseStepResult,
    TechnicalError: 'technical_error' as ExerciseStepResult
};