/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AirlineRefundMethod } from './airlineRefundMethod';
import { ModificationTime } from './modificationTime';
import { ModificationType } from './modificationType';

export interface FareRule { 
    modificationType: ModificationType;
    modificationTime: ModificationTime;
    /**
     * Determines if that type of modifications at this time is allowed
     */
    allowed: boolean;
    /**
     * Amount to be paid as penalty fee to perform the modification
     */
    fee?: string;
    /**
     * Percentage of the fare to be paid as penalty to perform the modification
     */
    percentage?: string;
    refundMethod?: AirlineRefundMethod;
}