/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The flow type for which the session is opened.
 */
export type FlowType = 'purchase' | 'exercise';

export const FlowType = {
    Purchase: 'purchase' as FlowType,
    Exercise: 'exercise' as FlowType
};