/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The gender of the passenger
 */
export type Gender = 'male' | 'female' | 'undisclosed' | 'unspecified';

export const Gender = {
    Male: 'male' as Gender,
    Female: 'female' as Gender,
    Undisclosed: 'undisclosed' as Gender,
    Unspecified: 'unspecified' as Gender
};