/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CfarItinerary } from './cfarItinerary';
import { CfarPrice } from './cfarPrice';
import { CfarStatus } from './cfarStatus';

/**
 * A CFAR Exercise
 */
export interface GetCfarExerciseCustomerResponse { 
    /**
     * Unique identifier for a CFAR exercise
     */
    id: string;
    /**
     * Unique identifier for a contract
     */
    contractId: string;
    cashRefundAllowance: string;
    hopperRefundCurrency: string;
    status: CfarStatus;
    contractExpiryDateTime: Date;
    itinerary: CfarItinerary;
    cfarPrices: Array<CfarPrice>;
}