/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The time at which the modification is requested
 */
export type ModificationTime = 'after_departure' | 'anytime' | 'before_departure';

export const ModificationTime = {
    AfterDeparture: 'after_departure' as ModificationTime,
    Anytime: 'anytime' as ModificationTime,
    BeforeDeparture: 'before_departure' as ModificationTime
};