/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The type of modifications in question in this fare rule
 */
export type ModificationType = 'cancellation' | 'change';

export const ModificationType = {
    Cancellation: 'cancellation' as ModificationType,
    Change: 'change' as ModificationType
};