/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PassengerType = 'adult' | 'child' | 'seated_infant' | 'lap_infant';

export const PassengerType = {
    Adult: 'adult' as PassengerType,
    Child: 'child' as PassengerType,
    SeatedInfant: 'seated_infant' as PassengerType,
    LapInfant: 'lap_infant' as PassengerType
};