/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type RequestType = 'post_booking' | 'reprice' | 'ancillary' | 'bundle' | 'fare';

export const RequestType = {
    PostBooking: 'post_booking' as RequestType,
    Reprice: 'reprice' as RequestType,
    Ancillary: 'ancillary' as RequestType,
    Bundle: 'bundle' as RequestType,
    Fare: 'fare' as RequestType
};