/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UiSource = 'banner_variant_a' | 'banner_variant_b' | 'banner_variant_c' | 'takeover';

export const UiSource = {
    BannerVariantA: 'banner_variant_a' as UiSource,
    BannerVariantB: 'banner_variant_b' as UiSource,
    BannerVariantC: 'banner_variant_c' as UiSource,
    Takeover: 'takeover' as UiSource
};