/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UiVariant = 'variant_a' | 'variant_b' | 'variant_c';

export const UiVariant = {
    A: 'variant_a' as UiVariant,
    B: 'variant_b' as UiVariant,
    C: 'variant_c' as UiVariant
};