/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ancillary } from './ancillary';
import { CfarItinerarySlice } from './cfarItinerarySlice';
import { PassengerPricing } from './passengerPricing';

/**
 * An object detailing the fare used to create a CFAR offer
 */
export interface CfarItinerary { 
    /**
     * List of pricing per passenger for a fare
     */
    passengerPricing: Array<PassengerPricing>;
    /**
     * Currency of pricing fields
     */
    currency: string;
    /**
     * List of fare slices included in this fare; only 1 (one way) or 2 (round trip) slices are allowed
     */
    slices: Array<CfarItinerarySlice>;
    /**
     * Ancillaries attached to a fare and their prices
     */
    ancillaries?: Array<Ancillary>;
    totalPrice: string;
}