/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FareClass } from './fareClass';

/**
 * An object detailing a segment of a fare slice
 */
export interface CfarItinerarySliceSegment { 
    /**
     * IATA airport code of origin
     */
    originAirport: string;
    /**
     * IATA airport code of destination
     */
    destinationAirport: string;
    /**
     * The local date and time of departure in ISO Local Date Time format
     */
    departureDateTime: string;
    /**
     * The local date and time of arrival in ISO Local Date Time format
     */
    arrivalDateTime: string;
    /**
     * The number of the flight
     */
    flightNumber: string;
    /**
     * The IATA airline code of the validating carrier for this segment
     */
    validatingCarrierCode: string;
    fareClass: FareClass;
}