/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AirlineRefundMethod } from './airlineRefundMethod';

/**
 * An update CFAR contract exercise request
 */
export interface MarkCfarContractExerciseCompleteRequest { 
    /**
     * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime; the date and time at which a contract exercise was completed
     */
    exerciseCompletedDateTime: Date;
    /**
     * The partner's share of the amount refunded to the customer to complete the CFAR contract exercise
     */
    hopperRefund: string;
    hopperRefundMethod: AirlineRefundMethod;
    airlineRefundAllowance: string;
    airlineRefundMethod: AirlineRefundMethod;
}