/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Platform } from './platform';

export interface Mobile { 
    /**
     * A unique identifier for the end-user's device, generated by the partner
     */
    id: string;
    platform?: Platform;
    type: string;
}