/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Unique screen name of the entry point where the user started the engagement
 */
export type Page = 'add_ons' | 'flight_list' | 'flight_details' | 'home' | 'itinerary' | 'payment' | 'summary';

export const Page = {
    AddOns: 'add_ons' as Page,
    FlightList: 'flight_list' as Page,
    FlightDetails: 'flight_details' as Page,
    Home: 'home' as Page,
    Itinerary: 'itinerary' as Page,
    Payment: 'payment' as Page,
    Summary: 'summary' as Page
};