/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PassengerType } from './passengerType';

/**
 * Type and number of passengers
 */
export interface PassengerCount { 
    /**
     * Number of passenger type
     */
    count: number;
    type: PassengerType;
}