/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Informations related to the airline's user. Should be included if known, but not if the user is anonymous
 */
export interface UserInfo { 
    /**
     * The airline's unique identifier for a user; can be an arbitrary string
     */
    airlineUserId: string;
    /**
     * A UTC [RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) datetime; the date and time at which a user's account was created
     */
    createdDateTime?: Date;
    /**
     * Number of prior bookings a user has made
     */
    previousBookings?: number;
}