/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Chrome } from './chrome';
import { Edge } from './edge';
import { Firefox } from './firefox';
import { InternetExplorer } from './internetExplorer';
import { Opera } from './opera';
import { OtherBrowser } from './otherBrowser';
import { Safari } from './safari';

export type Browser = Chrome | Edge | Firefox | InternetExplorer | Opera | OtherBrowser | Safari;