/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CfarItinerary } from './cfarItinerary';
import { MapString } from './mapString';
import { PaymentMethod } from './paymentMethod';

/**
 * A create CFAR contract request
 */
export interface CreateCfarContractRequest { 
    offerIds: Array<string>;
    itinerary: CfarItinerary;
    paymentMethod: PaymentMethod;
    extAttributes: MapString;
    pnrReference?: string;
}