/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Device } from './device';
import { UserInfo } from './userInfo';

export interface CreateAirlineSessionRequest { 
    userInfo?: UserInfo;
    device?: Device;
    /**
     * The point of sale related to the user. Must be an ISO 3166-1-alpha-2 country code
     */
    pointOfSale: string;
    /**
     * The language associated with the user. Must be an ISO_639-1 country code
     */
    language: string;
}