/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Desktop } from './desktop';
import { Mobile } from './mobile';
import { Tablet } from './tablet';

/**
 * The end-user's device
 */
export type Device = Desktop | Mobile | Tablet;