/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Fare class of the segment
 */
export type FareClass = 'basic_economy' | 'economy' | 'premium_economy' | 'business' | 'first';

export const FareClass = {
    BasicEconomy: 'basic_economy' as FareClass,
    Economy: 'economy' as FareClass,
    PremiumEconomy: 'premium_economy' as FareClass,
    Business: 'business' as FareClass,
    First: 'first' as FareClass
};