/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Android } from './android';
import { ChromeOs } from './chromeOs';
import { IOs } from './iOs';
import { Linux } from './linux';
import { MacOs } from './macOs';
import { OtherOs } from './otherOs';
import { Windows } from './windows';

export type OperatingSystem = Android | ChromeOs | IOs | Linux | MacOs | OtherOs | Windows;