/**
 * Airline API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OfflineReconciliation } from './offlineReconciliation';
import { SpreedlyToken } from './spreedlyToken';

/**
 * The payment method to be used for a transaction; offline_reconciliation indicates that the partner has collected payment from the user, and will reconcile with Hopper via a different process
 */
export type PaymentMethod = OfflineReconciliation | SpreedlyToken;